### ISSUE TITLE
an administrator can have validated data to ensure reliability.

### ISSUE THREAD

**Issue by idakam** [vinylShopFSA/vinylGraceShopper#11]

**Comment by paulde1** [comment]
- [ ] all admin requirements complete except I can't seem to get the information I need to verify admin status from req.user, tried debugging ,and reading documentation. 
- [ ] how admin middleware should look is location on branch "admin-update", "admin-experiment" contains the working front end functionality to be connected once I can figure out the admin verification. 
- [x] routes are locked for non admins on the backend, basically working on connecting functionality to front end.
